### ISSUE TITLE
Unable to find web.config file( you might changed or rename the web.config file)

### ISSUE THREAD

**Issue by akshayporwal** [ucdavis/Badges#8]
I am using VS 2015 professional. i cloned the project but unable to get web.config file.
 could you please help me how to get web.config file.

**Comment by srkirkland** [comment]
Here's an older version you can use (snapshot from before it was deleted): https://github.com/ucdavis/Badges/blob/f4e8f9e9c3dc7270a706366f9ffe8d8cc55b61c2/Badges/Web.config.

Note that the referenced storage accounts (for images and content) are no longer live so you'd have to replace them with your own accounts.
